export const COLORS = {
    main: '#ED6C00',
    loadingBackground: '#357df9',
    inputBorderColor: '#CAD6F4',
    placeholderTextColor: '#5B5B5B',
    lineColor: '#CAD6F4',
    rulesBackground: '#f2f9ff',
    secondLine: '#99AACC',
    modalBorder: '#CAD6FA',
    white: '#FFFFFF',
    drawerBackgroundColor: '#F7F9FF',
    drawerBorderColor: '#DDE6F8',
    iconInactiveColor: '#303030',
    boxBackground: '#F8FAFD',
    tagOnline: '#40CEB9',
    notificationButton: '#F92D92',
    menuText: '#5B5B5B',
    newTag: '#20B535',
    black: '#000000',
}
